Shapes not lining up
ValueError: Cannot feed value of shape (60000, 28, 28) for Tensor 'Placeholder_40:0', which has shape '(?, 784)'
-> Not lining up between x and x_tensor/x_train